#!/usr/bin/env python3
"""Generate Wave 2A Scenario Cards for P0 gaps."""

import json
from pathlib import Path

scenarios = []

# ============ DATA_ANALYSIS (5 scenarios) ============

scenarios.append({
    "id": "data.analysis.explain_metric.021",
    "title": "Explain what churn rate means",
    "domain": "data_analysis",
    "subdomain": "metrics_education",
    "scenario_level": 1,
    "domain_mode": "personal",
    "methodology": ["rapid_prototyping"],
    "artifact_profile": ["minimal"],
    "interaction_surface": ["chat", "opencode"],
    "user_input": "What is churn rate and why does it matter?",
    "user_intent": {"primary": "get_explanation", "secondary": [], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["zero_config", "dynamic_persona"], "domain_pack": None, "persona": "data_explainer", "autonomy": "autonomous", "explicit_config_needed": "none", "adaptive_elements": []},
    "expected_visible_behavior": ["provide concise definition", "explain business relevance", "give simple formula"],
    "internal_behavior": ["create SolveRequest", "classify as simple answer", "select lightweight model", "return answer", "write case trace"],
    "artifacts": {"inputs": [], "intermediate": [], "outputs": [{"name": "Answer", "type": "answer", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": [], "skills": [], "tools": [], "external": []},
    "policies": {"allow": ["generate_report"], "ask": [], "deny": ["file_write", "shell_mutation", "external_send"]},
    "gates": [],
    "memory": {"read": [], "write_candidates": [], "control_memory": []},
    "failure_modes": ["model_hallucination", "overly_technical_answer"],
    "configuration_effort": {"level": "zero_config", "notes": "No config needed."},
    "new_capabilities_introduced": [],
    "concept_questions": ["should simple metric explanations be cached"],
    "analysis_tags": ["simple_answer", "read_only", "zero_config", "data_analysis"],
    "execution_result": {"envelope_type": "Answer", "summary": "Answer: churn rate definition and formula", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "data.analysis.dataset_summary.022",
    "title": "Summarize customer dataset characteristics",
    "domain": "data_analysis",
    "subdomain": "exploratory_analysis",
    "scenario_level": 2,
    "domain_mode": "product",
    "methodology": ["lightweight_review"],
    "artifact_profile": ["report_based"],
    "interaction_surface": ["cli", "opencode"],
    "user_input": "Summarize the customer dataset. What are the key patterns?",
    "user_intent": {"primary": "explore_dataset", "secondary": ["identify_patterns", "flag_anomalies"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["generated_config", "dynamic_persona"], "domain_pack": "data-analysis", "persona": "data_analyst", "autonomy": "supervised", "explicit_config_needed": "low", "adaptive_elements": ["select_summary_depth", "choose_visualization"]},
    "expected_visible_behavior": ["acknowledge dataset review", "explain selected approach", "read dataset metadata", "return summary with patterns", "flag anomalies"],
    "internal_behavior": ["create SolveRequest", "classify as exploratory analysis", "build ContextBundle", "select data analyst agent", "generate SummaryReport", "write case trace"],
    "artifacts": {"inputs": ["dataset_metadata", "spreadsheet"], "intermediate": ["ContextBundle", "ScenarioDecision"], "outputs": [{"name": "DatasetSummary", "type": "report", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["data_analyst"], "skills": ["data.exploratory_analysis"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_project_files", "generate_report"], "ask": [], "deny": ["file_write", "external_send"]},
    "gates": [],
    "memory": {"read": ["previous_analyses"], "write_candidates": ["dataset_summary"], "control_memory": []},
    "failure_modes": ["dataset_too_large", "missing_metadata", "stale_data"],
    "configuration_effort": {"level": "generated_config", "notes": "Works with defaults; improves with data-analysis domain pack."},
    "new_capabilities_introduced": ["dataset_summary_artifact"],
    "concept_questions": ["should dataset summaries include visualizations"],
    "analysis_tags": ["context_answer", "report_artifact", "read_only", "dynamic_persona", "data_analysis"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: DatasetSummary with patterns and anomalies", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "data.analysis.quality_assessment.023",
    "title": "Assess data quality and propose cleaning plan",
    "domain": "data_analysis",
    "subdomain": "data_quality",
    "scenario_level": 3,
    "domain_mode": "enterprise",
    "methodology": ["checklist_based", "expert_review"],
    "artifact_profile": ["audit_heavy", "decision_log"],
    "interaction_surface": ["cli", "vscode"],
    "user_input": "Check the sales dataset for quality issues and propose a cleaning plan.",
    "user_intent": {"primary": "assess_data_quality", "secondary": ["identify_missing_values", "propose_cleaning"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["generated_config", "domain_pack", "dynamic_persona"], "domain_pack": "data-analysis", "persona": "data_quality_analyst", "autonomy": "supervised", "explicit_config_needed": "medium", "adaptive_elements": ["select_quality_dimensions", "choose_cleaning_strategy"]},
    "expected_visible_behavior": ["acknowledge quality check", "explain assessment dimensions", "read dataset", "return quality report with cleaning plan", "flag critical issues"],
    "internal_behavior": ["create SolveRequest", "classify as quality assessment", "build ContextBundle", "select data quality analyst agent", "generate QualityReport", "write case trace"],
    "artifacts": {"inputs": ["spreadsheet", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision"], "outputs": [{"name": "QualityReport", "type": "report", "lifecycle_state": "created", "domain_specific": False}, {"name": "CleaningPlan", "type": "plan", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["data_quality_analyst"], "skills": ["data.quality_assessment"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_project_files", "generate_report", "draft_communication"], "ask": [], "deny": ["file_write", "external_send"]},
    "gates": [],
    "memory": {"read": ["previous_quality_checks"], "write_candidates": ["quality_assessment_summary"], "control_memory": []},
    "failure_modes": ["dataset_too_large", "missing_quality_rules", "stale_data"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires data-analysis domain pack with quality framework."},
    "new_capabilities_introduced": ["quality_report_artifact"],
    "concept_questions": ["should data quality rules be domain-specific"],
    "analysis_tags": ["dry_run", "report_artifact", "read_only", "dynamic_persona", "data_analysis"],
    "execution_result": {"envelope_type": "Plan", "summary": "Plan: QualityReport and CleaningPlan", "confidence": "high", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": False, "spans": False, "alerts": []},
})

scenarios.append({
    "id": "data.analysis.predictive_model.024",
    "title": "Run predictive model on sales data with approval",
    "domain": "data_analysis",
    "subdomain": "predictive_modeling",
    "scenario_level": 4,
    "domain_mode": "enterprise",
    "methodology": ["spec_driven", "expert_review"],
    "artifact_profile": ["report_based", "decision_log"],
    "interaction_surface": ["cli", "api"],
    "user_input": "Run a churn prediction model on our customer data.",
    "user_intent": {"primary": "run_predictive_model", "secondary": ["interpret_results", "get_recommendations"], "ambiguity": "medium"},
    "wolf_configuration": {"mode": ["explicit_config", "domain_pack", "dynamic_persona"], "domain_pack": "data-analysis", "persona": "ml_engineer", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_model_type", "choose_features", "apply_model_gate"]},
    "expected_visible_behavior": ["acknowledge model request", "explain model approach", "request approval for data access", "run model after approval", "return prediction report"],
    "internal_behavior": ["create SolveRequest", "classify as predictive modeling", "build ContextBundle", "select ml engineer agent", "apply model_run policy", "request approval", "execute model", "generate PredictionReport", "write case trace"],
    "artifacts": {"inputs": ["database_query_result", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "PredictionReport", "type": "report", "lifecycle_state": "created", "domain_specific": False}, {"name": "FeatureImportance", "type": "table", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace", "DecisionLog"]},
    "capabilities": {"agents": ["ml_engineer"], "skills": ["data.predictive_modeling"], "tools": ["context.read", "shell.exec"], "external": []},
    "policies": {"allow": ["read_project_files", "run_model", "generate_report"], "ask": ["shell_mutation"], "deny": ["file_write", "external_send", "personal_data_exposure"]},
    "gates": [{"gate_name": "model_run_approval", "severity": "block", "rationale": "Running ML models on customer data requires explicit approval."}],
    "memory": {"read": ["previous_models"], "write_candidates": ["model_run_summary"], "control_memory": []},
    "failure_modes": ["missing_training_data", "model_bias", "data_leakage", "insufficient_features"],
    "configuration_effort": {"level": "explicit_config", "notes": "Requires data-analysis domain pack and model config."},
    "new_capabilities_introduced": ["prediction_report_artifact"],
    "concept_questions": ["should model predictions be persisted as artifacts"],
    "analysis_tags": ["governed_action", "tool_call", "expert_gate", "dynamic_persona", "data_analysis"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: PredictionReport with churn predictions", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": False, "alerts": ["model_run_failure"]},
})

scenarios.append({
    "id": "data.analysis.bi_dashboard.025",
    "title": "Build BI dashboard via Tableau MCP with policy",
    "domain": "data_analysis",
    "subdomain": "dashboard_creation",
    "scenario_level": 5,
    "domain_mode": "enterprise",
    "methodology": ["spec_driven", "checklist_based"],
    "artifact_profile": ["diagram_heavy", "decision_log"],
    "interaction_surface": ["cli", "mcp_client"],
    "user_input": "Create a sales dashboard in Tableau with real-time data from our warehouse.",
    "user_intent": {"primary": "create_dashboard", "secondary": ["connect_live_data", "configure_refresh"], "ambiguity": "medium"},
    "wolf_configuration": {"mode": ["domain_pack", "dynamic_persona", "llm_assisted_selection"], "domain_pack": "data-analysis", "persona": "bi_developer", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_mcp_tools", "choose_visualization_type", "apply_data_access_policy"]},
    "expected_visible_behavior": ["acknowledge dashboard request", "explain external connections", "request approval for Tableau MCP", "create dashboard after approval", "share dashboard link"],
    "internal_behavior": ["create SolveRequest", "classify as dashboard creation", "load Tableau MCP capability", "apply external_action policy", "request approval", "invoke MCP: create dashboard", "configure data source", "generate DashboardConfig", "write case trace"],
    "artifacts": {"inputs": ["database_query_result", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "DashboardConfig", "type": "config", "lifecycle_state": "created", "domain_specific": False}, {"name": "DataSourceMapping", "type": "mapping", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["bi_developer"], "skills": ["data.dashboard_creation"], "tools": ["context.read", "mcp.invoke"], "external": [{"name": "tableau.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "draft dashboard config locally without Tableau connection"}]},
    "policies": {"allow": ["read_project_files", "draft_communication"], "ask": ["external_send", "mcp.invoke"], "deny": ["auto_publish_without_review", "dangerous_shell"]},
    "gates": [{"gate_name": "external_action_approval", "severity": "block", "rationale": "Tableau MCP may create external resources. Approval required."}, {"gate_name": "data_access_approval", "severity": "block", "rationale": "Real-time warehouse access requires data governance approval."}],
    "memory": {"read": ["previous_dashboards"], "write_candidates": ["dashboard_creation_summary"], "control_memory": []},
    "failure_modes": ["tableau_mcp_unavailable", "warehouse_connection_failed", "policy_conflict_on_data_access", "dashboard_permission_error"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires data-analysis domain pack and Tableau MCP setup."},
    "new_capabilities_introduced": ["dashboard_config_artifact"],
    "concept_questions": ["should dashboard creation require data steward approval"],
    "analysis_tags": ["external_action", "mcp", "governed_action", "multi_agent", "data_analysis"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: DashboardConfig and DataSourceMapping", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": True, "alerts": ["mcp_failure", "dashboard_refresh_error"]},
})

# ============ HR_RECRUITING (5 scenarios) ============

scenarios.append({
    "id": "hr.recruit.explain_process.026",
    "title": "Explain the hiring process for senior engineers",
    "domain": "hr_recruiting",
    "subdomain": "process_education",
    "scenario_level": 1,
    "domain_mode": "personal",
    "methodology": ["rapid_prototyping"],
    "artifact_profile": ["minimal"],
    "interaction_surface": ["chat", "opencode"],
    "user_input": "What is our hiring process for senior engineers?",
    "user_intent": {"primary": "get_explanation", "secondary": [], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["zero_config", "dynamic_persona"], "domain_pack": None, "persona": "hr_coordinator", "autonomy": "autonomous", "explicit_config_needed": "none", "adaptive_elements": []},
    "expected_visible_behavior": ["provide concise process overview", "explain stages", "mention timelines"],
    "internal_behavior": ["create SolveRequest", "classify as simple answer", "select lightweight model", "return answer", "write case trace"],
    "artifacts": {"inputs": [], "intermediate": [], "outputs": [{"name": "Answer", "type": "answer", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": [], "skills": [], "tools": [], "external": []},
    "policies": {"allow": ["generate_report"], "ask": [], "deny": ["file_write", "shell_mutation", "external_send"]},
    "gates": [],
    "memory": {"read": [], "write_candidates": [], "control_memory": []},
    "failure_modes": ["model_hallucination", "outdated_process_info"],
    "configuration_effort": {"level": "zero_config", "notes": "No config needed."},
    "new_capabilities_introduced": [],
    "concept_questions": ["should HR process info be cached"],
    "analysis_tags": ["simple_answer", "read_only", "zero_config", "hr_recruiting"],
    "execution_result": {"envelope_type": "Answer", "summary": "Answer: hiring process overview", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "hr.recruit.candidate_compare.027",
    "title": "Compare two candidate profiles",
    "domain": "hr_recruiting",
    "subdomain": "candidate_evaluation",
    "scenario_level": 2,
    "domain_mode": "product",
    "methodology": ["checklist_based", "lightweight_review"],
    "artifact_profile": ["evidence_table", "decision_log"],
    "interaction_surface": ["cli", "opencode"],
    "user_input": "Compare these two candidates for the senior engineer role.",
    "user_intent": {"primary": "compare_candidates", "secondary": ["identify_strengths", "flag_gaps"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["generated_config", "dynamic_persona"], "domain_pack": "hr-recruiting", "persona": "recruiting_coordinator", "autonomy": "supervised", "explicit_config_needed": "low", "adaptive_elements": ["select_comparison_criteria", "choose_scoring_method"]},
    "expected_visible_behavior": ["acknowledge comparison request", "explain criteria briefly", "read candidate profiles", "return comparison matrix", "flag key differences"],
    "internal_behavior": ["create SolveRequest", "classify as candidate evaluation", "build ContextBundle", "select recruiting coordinator agent", "generate ComparisonMatrix", "write case trace"],
    "artifacts": {"inputs": ["uploaded_document"], "intermediate": ["ContextBundle", "ScenarioDecision"], "outputs": [{"name": "ComparisonMatrix", "type": "table", "lifecycle_state": "created", "domain_specific": True}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["recruiting_coordinator"], "skills": ["hr.candidate_comparison"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_uploaded_document", "generate_report"], "ask": [], "deny": ["file_write", "external_send", "personal_data_exposure"]},
    "gates": [],
    "memory": {"read": ["previous_evaluations"], "write_candidates": ["candidate_comparison_summary"], "control_memory": []},
    "failure_modes": ["missing_jd_context", "pii_in_resumes", "bias_in_comparison"],
    "configuration_effort": {"level": "generated_config", "notes": "Works with defaults; improves with hr-recruiting domain pack."},
    "new_capabilities_introduced": ["comparison_matrix_artifact"],
    "concept_questions": ["should candidate comparison include bias detection"],
    "analysis_tags": ["context_answer", "report_artifact", "personal_data", "dynamic_persona", "hr_recruiting"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: ComparisonMatrix with candidate evaluation", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "hr.recruit.interview_plan.028",
    "title": "Create structured interview plan",
    "domain": "hr_recruiting",
    "subdomain": "interview_design",
    "scenario_level": 3,
    "domain_mode": "enterprise",
    "methodology": ["spec_driven", "checklist_based"],
    "artifact_profile": ["spec_based", "decision_log"],
    "interaction_surface": ["cli", "vscode"],
    "user_input": "Create a structured interview plan for the senior engineer role.",
    "user_intent": {"primary": "design_interview_plan", "secondary": ["select_competencies", "assign_interviewers"], "ambiguity": "medium"},
    "wolf_configuration": {"mode": ["generated_config", "domain_pack", "dynamic_persona"], "domain_pack": "hr-recruiting", "persona": "talent_acquisition_lead", "autonomy": "supervised", "explicit_config_needed": "medium", "adaptive_elements": ["select_competency_framework", "choose_interview_stages"]},
    "expected_visible_behavior": ["acknowledge interview plan request", "explain competency framework", "read job description", "return structured interview plan", "suggest interviewer assignments"],
    "internal_behavior": ["create SolveRequest", "classify as interview design", "build ContextBundle", "select talent acquisition lead agent", "generate InterviewPlan", "write case trace"],
    "artifacts": {"inputs": ["uploaded_document", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision"], "outputs": [{"name": "InterviewPlan", "type": "plan", "lifecycle_state": "created", "domain_specific": True}, {"name": "CompetencyMatrix", "type": "matrix", "lifecycle_state": "created", "domain_specific": True}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["talent_acquisition_lead"], "skills": ["hr.interview_design"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_project_files", "generate_report", "draft_communication"], "ask": [], "deny": ["file_write", "external_send"]},
    "gates": [],
    "memory": {"read": ["previous_interview_plans"], "write_candidates": ["interview_plan_summary"], "control_memory": []},
    "failure_modes": ["missing_jd_context", "incomplete_competency_list", "stale_interview_framework"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires hr-recruiting domain pack with competency framework."},
    "new_capabilities_introduced": ["interview_plan_artifact"],
    "concept_questions": ["should interview plans be versioned per role"],
    "analysis_tags": ["dry_run", "report_artifact", "read_only", "dynamic_persona", "hr_recruiting"],
    "execution_result": {"envelope_type": "Plan", "summary": "Plan: InterviewPlan and CompetencyMatrix", "confidence": "high", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": False, "spans": False, "alerts": []},
})

scenarios.append({
    "id": "hr.recruit.send_offer.029",
    "title": "Send offer letter with approval gate",
    "domain": "hr_recruiting",
    "subdomain": "offer_management",
    "scenario_level": 4,
    "domain_mode": "enterprise",
    "methodology": ["checklist_based", "compliance_review"],
    "artifact_profile": ["draft_communication", "decision_log"],
    "interaction_surface": ["cli", "api"],
    "user_input": "Send an offer letter to the selected candidate.",
    "user_intent": {"primary": "send_offer_letter", "secondary": ["customize_terms", "attach_documents"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["explicit_config", "domain_pack", "dynamic_persona"], "domain_pack": "hr-recruiting", "persona": "hr_manager", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_offer_template", "choose_compensation_package", "apply_approval_gate"]},
    "expected_visible_behavior": ["acknowledge offer request", "explain offer process", "draft offer letter", "request approval for send", "send after approval", "confirm delivery"],
    "internal_behavior": ["create SolveRequest", "classify as offer management", "build ContextBundle", "select hr manager agent", "apply send_approval policy", "draft EmailDraft", "request approval", "send after approval", "write case trace"],
    "artifacts": {"inputs": ["uploaded_document", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "EmailDraft", "type": "draft", "lifecycle_state": "created", "domain_specific": False}, {"name": "OfferConfirmation", "type": "confirmation", "lifecycle_state": "created", "domain_specific": True}], "persisted": ["CaseTrace", "DecisionLog"]},
    "capabilities": {"agents": ["hr_manager"], "skills": ["hr.offer_management"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_project_files", "draft_communication", "generate_report"], "ask": ["external_send"], "deny": ["file_write", "personal_data_exposure"]},
    "gates": [{"gate_name": "offer_send_approval", "severity": "block", "rationale": "Sending offer letters involves legal and financial commitments. Approval required."}],
    "memory": {"read": ["previous_offers"], "write_candidates": ["offer_send_summary"], "control_memory": []},
    "failure_modes": ["missing_candidate_data", "policy_conflict_on_send", "offer_template_outdated"],
    "configuration_effort": {"level": "explicit_config", "notes": "Requires hr-recruiting pack with offer templates."},
    "new_capabilities_introduced": ["offer_confirmation_artifact"],
    "concept_questions": ["should offer letters require legal review gate"],
    "analysis_tags": ["governed_action", "external_send", "expert_gate", "dynamic_persona", "hr_recruiting"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: EmailDraft and OfferConfirmation", "confidence": "high", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": False, "alerts": ["offer_send_failure"]},
})

scenarios.append({
    "id": "hr.recruit.full_cycle.030",
    "title": "Run full hiring cycle via ATS and background check",
    "domain": "hr_recruiting",
    "subdomain": "full_cycle_hiring",
    "scenario_level": 5,
    "domain_mode": "enterprise",
    "methodology": ["spec_driven", "checklist_based"],
    "artifact_profile": ["audit_heavy", "decision_log"],
    "interaction_surface": ["cli", "mcp_client"],
    "user_input": "Run the full hiring cycle for the senior engineer role: screen resumes, schedule interviews, collect feedback, run background check, and send offer.",
    "user_intent": {"primary": "run_full_hiring_cycle", "secondary": ["coordinate_schedule", "collect_feedback", "verify_background"], "ambiguity": "high"},
    "wolf_configuration": {"mode": ["domain_pack", "dynamic_persona", "llm_assisted_selection"], "domain_pack": "hr-recruiting", "persona": "talent_acquisition_lead", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_ats_tools", "choose_background_check_provider", "apply_workflow"]},
    "expected_visible_behavior": ["acknowledge full cycle request", "explain workflow steps", "request approval for ATS access", "screen resumes", "schedule interviews", "collect feedback", "request approval for background check", "send offer after approval", "confirm completion"],
    "internal_behavior": ["create SolveRequest", "classify as full cycle hiring", "load ATS MCP capability", "apply external_action policy", "request approval", "screen resumes", "schedule interviews via MCP", "collect feedback", "request background check approval", "invoke background check API", "draft offer", "request offer approval", "send offer", "write case trace"],
    "artifacts": {"inputs": ["uploaded_document", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision", "ExecutionPlan"], "outputs": [{"name": "HiringCycleReport", "type": "report", "lifecycle_state": "created", "domain_specific": True}, {"name": "BackgroundCheckResult", "type": "report", "lifecycle_state": "created", "domain_specific": True}], "persisted": ["CaseTrace", "DecisionLog"]},
    "capabilities": {"agents": ["talent_acquisition_lead"], "skills": ["hr.full_cycle_hiring"], "tools": ["context.read", "mcp.invoke"], "external": [{"name": "ats.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "manage hiring locally without ATS sync"}, {"name": "background_check.api", "type": "direct_api", "trust_level": "untrusted", "fallback_action": "flag candidate for manual background verification"}]},
    "policies": {"allow": ["read_project_files", "draft_communication", "generate_report"], "ask": ["external_send", "mcp.invoke"], "deny": ["auto_hire_without_review", "personal_data_exposure"]},
    "gates": [{"gate_name": "ats_access_approval", "severity": "block", "rationale": "ATS access may update external systems. Approval required."}, {"gate_name": "background_check_approval", "severity": "block", "rationale": "Background checks involve sensitive data processing. Approval required."}, {"gate_name": "offer_send_approval", "severity": "block", "rationale": "Sending offers involves legal and financial commitments. Approval required."}],
    "memory": {"read": ["previous_hiring_cycles", "hiring_templates"], "write_candidates": ["hiring_cycle_summary"], "control_memory": ["active_hiring_flag"]},
    "failure_modes": ["ats_unavailable", "background_check_timeout", "policy_conflict_on_external_send", "candidate_withdrawal"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires hr-recruiting pack with ATS and background check integrations."},
    "new_capabilities_introduced": ["hiring_cycle_report_artifact"],
    "concept_questions": ["should full cycle hiring require HR director approval"],
    "analysis_tags": ["external_action", "mcp", "governed_action", "multi_agent", "personal_data", "hr_recruiting"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: HiringCycleReport and BackgroundCheckResult", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": True, "alerts": ["ats_failure", "background_check_timeout", "offer_send_failure"]},
})

# ============ FINANCE_OPS (4 scenarios) ============

scenarios.append({
    "id": "finance.explain_cash_flow.031",
    "title": "Explain cash flow basics",
    "domain": "finance_ops",
    "subdomain": "financial_education",
    "scenario_level": 1,
    "domain_mode": "personal",
    "methodology": ["rapid_prototyping"],
    "artifact_profile": ["minimal"],
    "interaction_surface": ["chat", "opencode"],
    "user_input": "What is cash flow and why is it important?",
    "user_intent": {"primary": "get_explanation", "secondary": [], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["zero_config", "dynamic_persona"], "domain_pack": None, "persona": "financial_explainer", "autonomy": "autonomous", "explicit_config_needed": "none", "adaptive_elements": []},
    "expected_visible_behavior": ["provide concise definition", "explain business relevance", "give simple example"],
    "internal_behavior": ["create SolveRequest", "classify as simple answer", "select lightweight model", "return answer", "write case trace"],
    "artifacts": {"inputs": [], "intermediate": [], "outputs": [{"name": "Answer", "type": "answer", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": [], "skills": [], "tools": [], "external": []},
    "policies": {"allow": ["generate_report"], "ask": [], "deny": ["file_write", "shell_mutation", "external_send"]},
    "gates": [],
    "memory": {"read": [], "write_candidates": [], "control_memory": []},
    "failure_modes": ["model_hallucination", "overly_technical_answer"],
    "configuration_effort": {"level": "zero_config", "notes": "No config needed."},
    "new_capabilities_introduced": [],
    "concept_questions": ["should financial definitions include regulatory context"],
    "analysis_tags": ["simple_answer", "read_only", "zero_config", "finance_ops"],
    "execution_result": {"envelope_type": "Answer", "summary": "Answer: cash flow definition and importance", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "finance.invoice_review.032",
    "title": "Review invoice for anomalies",
    "domain": "finance_ops",
    "subdomain": "invoice_processing",
    "scenario_level": 2,
    "domain_mode": "product",
    "methodology": ["checklist_based", "lightweight_review"],
    "artifact_profile": ["report_based"],
    "interaction_surface": ["cli", "opencode"],
    "user_input": "Review this invoice for any anomalies or discrepancies.",
    "user_intent": {"primary": "review_invoice", "secondary": ["flag_anomalies", "verify_amounts"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["generated_config", "dynamic_persona"], "domain_pack": "finance-ops", "persona": "finance_controller", "autonomy": "supervised", "explicit_config_needed": "low", "adaptive_elements": ["select_review_depth", "choose_anomaly_rules"]},
    "expected_visible_behavior": ["acknowledge invoice review", "explain review scope", "read invoice data", "return anomaly report", "flag discrepancies"],
    "internal_behavior": ["create SolveRequest", "classify as invoice review", "build ContextBundle", "select finance controller agent", "generate AnomalyReport", "write case trace"],
    "artifacts": {"inputs": ["spreadsheet", "uploaded_document"], "intermediate": ["ContextBundle", "ScenarioDecision"], "outputs": [{"name": "AnomalyReport", "type": "report", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["finance_controller"], "skills": ["finance.invoice_review"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_project_files", "generate_report"], "ask": [], "deny": ["file_write", "external_send", "financial_action_without_approval"]},
    "gates": [],
    "memory": {"read": ["previous_invoices"], "write_candidates": ["invoice_review_summary"], "control_memory": []},
    "failure_modes": ["missing_invoice_data", "currency_mismatch", "duplicate_invoice"],
    "configuration_effort": {"level": "generated_config", "notes": "Works with defaults; improves with finance-ops domain pack."},
    "new_capabilities_introduced": ["anomaly_report_artifact"],
    "concept_questions": ["should invoice reviews auto-flag duplicates"],
    "analysis_tags": ["context_answer", "report_artifact", "read_only", "dynamic_persona", "finance_ops"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: AnomalyReport with invoice discrepancies", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "finance.budget_variance.033",
    "title": "Analyze budget variance with approval",
    "domain": "finance_ops",
    "subdomain": "budget_control",
    "scenario_level": 4,
    "domain_mode": "enterprise",
    "methodology": ["checklist_based", "compliance_review"],
    "artifact_profile": ["audit_heavy", "decision_log"],
    "interaction_surface": ["cli", "api"],
    "user_input": "Analyze the Q2 budget variance and approve any necessary adjustments.",
    "user_intent": {"primary": "analyze_budget_variance", "secondary": ["identify_overspend", "propose_adjustments"], "ambiguity": "medium"},
    "wolf_configuration": {"mode": ["explicit_config", "domain_pack", "dynamic_persona"], "domain_pack": "finance-ops", "persona": "cfo", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_variance_threshold", "choose_adjustment_strategy", "apply_approval_gate"]},
    "expected_visible_behavior": ["acknowledge variance analysis", "explain analysis scope", "read budget data", "return variance report", "request approval for adjustments", "apply after approval"],
    "internal_behavior": ["create SolveRequest", "classify as budget control", "build ContextBundle", "select cfo agent", "apply financial_action policy", "generate VarianceReport", "request approval", "apply adjustments", "write case trace"],
    "artifacts": {"inputs": ["spreadsheet", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "VarianceReport", "type": "report", "lifecycle_state": "created", "domain_specific": False}, {"name": "AdjustmentLog", "type": "log", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace", "DecisionLog"]},
    "capabilities": {"agents": ["cfo"], "skills": ["finance.budget_control"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_project_files", "generate_report"], "ask": ["financial_action"], "deny": ["file_write", "external_send", "personal_data_exposure"]},
    "gates": [{"gate_name": "budget_adjustment_approval", "severity": "block", "rationale": "Budget adjustments affect financial planning. Approval required."}],
    "memory": {"read": ["previous_budgets"], "write_candidates": ["budget_adjustment_summary"], "control_memory": []},
    "failure_modes": ["missing_budget_data", "stale_actuals", "policy_conflict_on_adjustment"],
    "configuration_effort": {"level": "explicit_config", "notes": "Requires finance-ops pack with budget framework."},
    "new_capabilities_introduced": ["variance_report_artifact"],
    "concept_questions": ["should budget adjustments require board approval"],
    "analysis_tags": ["governed_action", "financial_action", "expert_gate", "dynamic_persona", "finance_ops"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: VarianceReport and AdjustmentLog", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": False, "alerts": ["budget_overspend_detected"]},
})

scenarios.append({
    "id": "finance.payroll_integration.034",
    "title": "Process payroll via ERP and bank API",
    "domain": "finance_ops",
    "subdomain": "payroll_processing",
    "scenario_level": 5,
    "domain_mode": "enterprise",
    "methodology": ["spec_driven", "checklist_based"],
    "artifact_profile": ["audit_heavy", "decision_log"],
    "interaction_surface": ["cli", "mcp_client"],
    "user_input": "Process this month's payroll via ERP and initiate bank transfers.",
    "user_intent": {"primary": "process_payroll", "secondary": ["calculate_taxes", "initiate_transfers"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["domain_pack", "dynamic_persona", "llm_assisted_selection"], "domain_pack": "finance-ops", "persona": "payroll_manager", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_erp_tools", "choose_bank_api", "apply_payroll_policy"]},
    "expected_visible_behavior": ["acknowledge payroll request", "explain processing steps", "read payroll data", "request approval for transfers", "process after approval", "confirm completion"],
    "internal_behavior": ["create SolveRequest", "classify as payroll processing", "load ERP MCP capability", "apply financial_action policy", "request approval", "invoke ERP: process payroll", "initiate bank transfers", "generate PayrollReport", "write case trace"],
    "artifacts": {"inputs": ["spreadsheet", "docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "PayrollReport", "type": "report", "lifecycle_state": "created", "domain_specific": True}, {"name": "TransferConfirmation", "type": "confirmation", "lifecycle_state": "created", "domain_specific": True}], "persisted": ["CaseTrace", "DecisionLog"]},
    "capabilities": {"agents": ["payroll_manager"], "skills": ["finance.payroll_processing"], "tools": ["context.read", "mcp.invoke"], "external": [{"name": "erp.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "process payroll locally without ERP sync"}, {"name": "bank.api", "type": "direct_api", "trust_level": "untrusted", "fallback_action": "generate transfer instructions for manual processing"}]},
    "policies": {"allow": ["read_project_files", "generate_report"], "ask": ["financial_action", "mcp.invoke"], "deny": ["auto_transfer_without_approval", "personal_data_exposure"]},
    "gates": [{"gate_name": "payroll_approval", "severity": "block", "rationale": "Payroll processing affects employee compensation. Approval required."}, {"gate_name": "bank_transfer_approval", "severity": "block", "rationale": "Bank transfers are irreversible. Approval required."}],
    "memory": {"read": ["previous_payrolls"], "write_candidates": ["payroll_summary"], "control_memory": []},
    "failure_modes": ["erp_unavailable", "bank_api_timeout", "policy_conflict_on_transfer", "insufficient_funds"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires finance-ops pack with ERP and bank integrations."},
    "new_capabilities_introduced": ["payroll_report_artifact"],
    "concept_questions": ["should payroll require dual approval"],
    "analysis_tags": ["external_action", "mcp", "governed_action", "financial_action", "multi_agent", "finance_ops"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: PayrollReport and TransferConfirmation", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": True, "alerts": ["erp_failure", "bank_transfer_timeout", "payroll_error"]},
})

# ============ PRODUCT_MANAGEMENT (4 scenarios) ============

scenarios.append({
    "id": "product.explain_prioritization.035",
    "title": "Explain product prioritization frameworks",
    "domain": "product_management",
    "subdomain": "process_education",
    "scenario_level": 1,
    "domain_mode": "personal",
    "methodology": ["rapid_prototyping"],
    "artifact_profile": ["minimal"],
    "interaction_surface": ["chat", "opencode"],
    "user_input": "What prioritization frameworks should we use?",
    "user_intent": {"primary": "get_explanation", "secondary": [], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["zero_config", "dynamic_persona"], "domain_pack": None, "persona": "product_explainer", "autonomy": "autonomous", "explicit_config_needed": "none", "adaptive_elements": []},
    "expected_visible_behavior": ["provide concise overview", "explain frameworks", "suggest when to use each"],
    "internal_behavior": ["create SolveRequest", "classify as simple answer", "select lightweight model", "return answer", "write case trace"],
    "artifacts": {"inputs": [], "intermediate": [], "outputs": [{"name": "Answer", "type": "answer", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": [], "skills": [], "tools": [], "external": []},
    "policies": {"allow": ["generate_report"], "ask": [], "deny": ["file_write", "shell_mutation", "external_send"]},
    "gates": [],
    "memory": {"read": [], "write_candidates": [], "control_memory": []},
    "failure_modes": ["model_hallucination", "outdated_framework_info"],
    "configuration_effort": {"level": "zero_config", "notes": "No config needed."},
    "new_capabilities_introduced": [],
    "concept_questions": ["should prioritization frameworks be domain-specific"],
    "analysis_tags": ["simple_answer", "read_only", "zero_config", "product_management"],
    "execution_result": {"envelope_type": "Answer", "summary": "Answer: prioritization frameworks overview", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "product.jira.ticket.036",
    "title": "Create Jira ticket with approval gate",
    "domain": "product_management",
    "subdomain": "ticket_creation",
    "scenario_level": 4,
    "domain_mode": "enterprise",
    "methodology": ["checklist_based", "spec_driven"],
    "artifact_profile": ["spec_based", "decision_log"],
    "interaction_surface": ["cli", "mcp_client"],
    "user_input": "Create a Jira ticket for the new authentication feature.",
    "user_intent": {"primary": "create_ticket", "secondary": ["assign_team", "set_priority"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["explicit_config", "domain_pack", "dynamic_persona"], "domain_pack": "product-management", "persona": "product_manager", "autonomy": "gated", "explicit_config_needed": "medium", "adaptive_elements": ["select_ticket_template", "choose_priority", "apply_approval_gate"]},
    "expected_visible_behavior": ["acknowledge ticket request", "explain ticket fields", "request approval for creation", "create ticket after approval", "confirm creation"],
    "internal_behavior": ["create SolveRequest", "classify as ticket creation", "load Jira MCP capability", "apply external_action policy", "draft TicketSpec", "request approval", "invoke MCP: create ticket", "write case trace"],
    "artifacts": {"inputs": ["docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "TicketSpec", "type": "spec", "lifecycle_state": "created", "domain_specific": False}, {"name": "JiraTicketLink", "type": "link", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["product_manager"], "skills": ["product.ticket_creation"], "tools": ["context.read", "mcp.invoke"], "external": [{"name": "jira.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "draft ticket locally without Jira creation"}]},
    "policies": {"allow": ["read_project_files", "draft_communication"], "ask": ["external_send", "mcp.invoke"], "deny": ["auto_assign_without_review", "dangerous_shell"]},
    "gates": [{"gate_name": "ticket_creation_approval", "severity": "block", "rationale": "Jira ticket creation affects team workload. Approval required."}],
    "memory": {"read": ["previous_tickets"], "write_candidates": ["ticket_creation_summary"], "control_memory": []},
    "failure_modes": ["jira_unavailable", "missing_ticket_template", "policy_conflict_on_external_action"],
    "configuration_effort": {"level": "explicit_config", "notes": "Requires product-management pack with Jira integration."},
    "new_capabilities_introduced": ["ticket_spec_artifact"],
    "concept_questions": ["should ticket creation require team lead approval"],
    "analysis_tags": ["external_action", "mcp", "governed_action", "dynamic_persona", "product_management"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: TicketSpec and JiraTicketLink", "confidence": "high", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": False, "alerts": ["jira_failure"]},
})

scenarios.append({
    "id": "product.roadmap.sync.037",
    "title": "Sync roadmap across Jira, Confluence, and Slack",
    "domain": "product_management",
    "subdomain": "roadmap_sync",
    "scenario_level": 5,
    "domain_mode": "enterprise",
    "methodology": ["spec_driven", "checklist_based"],
    "artifact_profile": ["diagram_heavy", "decision_log"],
    "interaction_surface": ["cli", "mcp_client"],
    "user_input": "Sync the Q3 roadmap across Jira, Confluence, and notify the team on Slack.",
    "user_intent": {"primary": "sync_roadmap", "secondary": ["update_jira", "update_confluence", "notify_team"], "ambiguity": "medium"},
    "wolf_configuration": {"mode": ["domain_pack", "dynamic_persona", "llm_assisted_selection"], "domain_pack": "product-management", "persona": "product_manager", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_mcp_tools", "choose_sync_strategy", "apply_notification_policy"]},
    "expected_visible_behavior": ["acknowledge sync request", "explain sync scope", "read roadmap data", "request approval for external updates", "sync after approval", "confirm completion"],
    "internal_behavior": ["create SolveRequest", "classify as roadmap sync", "load Jira MCP", "load Confluence MCP", "load Slack MCP", "apply external_action policy", "request approval", "invoke MCP: update Jira", "invoke MCP: update Confluence", "invoke MCP: notify Slack", "generate SyncReport", "write case trace"],
    "artifacts": {"inputs": ["docs", "spreadsheet"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "SyncReport", "type": "report", "lifecycle_state": "created", "domain_specific": False}, {"name": "RoadmapDiagram", "type": "diagram", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["product_manager"], "skills": ["product.roadmap_sync"], "tools": ["context.read", "mcp.invoke"], "external": [{"name": "jira.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "draft updates locally without Jira sync"}, {"name": "confluence.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "draft docs locally without Confluence sync"}, {"name": "slack.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "log notification to CaseTrace without sending"}]},
    "policies": {"allow": ["read_project_files", "draft_communication"], "ask": ["external_send", "mcp.invoke"], "deny": ["auto_publish_without_review", "dangerous_shell"]},
    "gates": [{"gate_name": "external_update_approval", "severity": "block", "rationale": "External updates may affect team visibility. Approval required."}, {"gate_name": "notification_approval", "severity": "notify", "rationale": "Team notification is reversible but should be acknowledged."}],
    "memory": {"read": ["previous_roadmaps"], "write_candidates": ["roadmap_sync_summary"], "control_memory": []},
    "failure_modes": ["jira_unavailable", "confluence_unavailable", "slack_unavailable", "policy_conflict_on_sync"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires product-management pack with Jira, Confluence, Slack integrations."},
    "new_capabilities_introduced": ["sync_report_artifact"],
    "concept_questions": ["should roadmap sync require product director approval"],
    "analysis_tags": ["external_action", "mcp", "governed_action", "multi_agent", "product_management"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: SyncReport and RoadmapDiagram", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": True, "alerts": ["mcp_failure", "sync_conflict"]},
})

# ============ RESEARCH (4 scenarios) ============

scenarios.append({
    "id": "research.explain_methodology.038",
    "title": "Explain systematic literature review methodology",
    "domain": "research",
    "subdomain": "methodology_education",
    "scenario_level": 1,
    "domain_mode": "personal",
    "methodology": ["rapid_prototyping"],
    "artifact_profile": ["minimal"],
    "interaction_surface": ["chat", "opencode"],
    "user_input": "What is a systematic literature review and how do I conduct one?",
    "user_intent": {"primary": "get_explanation", "secondary": [], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["zero_config", "dynamic_persona"], "domain_pack": None, "persona": "research_explainer", "autonomy": "autonomous", "explicit_config_needed": "none", "adaptive_elements": []},
    "expected_visible_behavior": ["provide concise definition", "explain steps", "mention tools"],
    "internal_behavior": ["create SolveRequest", "classify as simple answer", "select lightweight model", "return answer", "write case trace"],
    "artifacts": {"inputs": [], "intermediate": [], "outputs": [{"name": "Answer", "type": "answer", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": [], "skills": [], "tools": [], "external": []},
    "policies": {"allow": ["generate_report"], "ask": [], "deny": ["file_write", "shell_mutation", "external_send"]},
    "gates": [],
    "memory": {"read": [], "write_candidates": [], "control_memory": []},
    "failure_modes": ["model_hallucination", "outdated_methodology_info"],
    "configuration_effort": {"level": "zero_config", "notes": "No config needed."},
    "new_capabilities_introduced": [],
    "concept_questions": ["should research methodology be domain-specific"],
    "analysis_tags": ["simple_answer", "read_only", "zero_config", "research"],
    "execution_result": {"envelope_type": "Answer", "summary": "Answer: systematic literature review methodology", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "research.paper.summary.039",
    "title": "Summarize recent paper on neural networks",
    "domain": "research",
    "subdomain": "literature_review",
    "scenario_level": 2,
    "domain_mode": "product",
    "methodology": ["lightweight_review"],
    "artifact_profile": ["report_based"],
    "interaction_surface": ["cli", "opencode"],
    "user_input": "Summarize the recent paper on neural networks from arXiv.",
    "user_intent": {"primary": "summarize_paper", "secondary": ["identify_key_findings", "flag_limitations"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["generated_config", "dynamic_persona"], "domain_pack": "research", "persona": "research_analyst", "autonomy": "supervised", "explicit_config_needed": "low", "adaptive_elements": ["select_summary_depth", "choose_focus_areas"]},
    "expected_visible_behavior": ["acknowledge paper summary", "explain approach", "read paper", "return summary with key findings", "flag limitations"],
    "internal_behavior": ["create SolveRequest", "classify as literature review", "build ContextBundle", "select research analyst agent", "generate PaperSummary", "write case trace"],
    "artifacts": {"inputs": ["uploaded_document"], "intermediate": ["ContextBundle", "ScenarioDecision"], "outputs": [{"name": "PaperSummary", "type": "summary", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["research_analyst"], "skills": ["research.paper_summary"], "tools": ["context.read"], "external": []},
    "policies": {"allow": ["read_uploaded_document", "generate_report"], "ask": [], "deny": ["file_write", "external_send"]},
    "gates": [],
    "memory": {"read": ["previous_summaries"], "write_candidates": ["paper_summary"], "control_memory": []},
    "failure_modes": ["missing_paper_access", "paper_too_long", "stale_paper_version"],
    "configuration_effort": {"level": "generated_config", "notes": "Works with defaults; improves with research domain pack."},
    "new_capabilities_introduced": ["paper_summary_artifact"],
    "concept_questions": ["should paper summaries include citation suggestions"],
    "analysis_tags": ["context_answer", "report_artifact", "read_only", "dynamic_persona", "research"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: PaperSummary with key findings", "confidence": "high", "trace_reference": "CaseTrace"},
})

scenarios.append({
    "id": "research.systematic.scan.040",
    "title": "Run systematic literature scan with citation manager",
    "domain": "research",
    "subdomain": "systematic_review",
    "scenario_level": 5,
    "domain_mode": "enterprise",
    "methodology": ["research_protocol", "expert_review"],
    "artifact_profile": ["evidence_table", "report_based"],
    "interaction_surface": ["cli", "mcp_client"],
    "user_input": "Run a systematic literature scan on AI safety and sync results with Zotero.",
    "user_intent": {"primary": "run_systematic_scan", "secondary": ["sync_citations", "organize_library"], "ambiguity": "low"},
    "wolf_configuration": {"mode": ["domain_pack", "dynamic_persona", "llm_assisted_selection"], "domain_pack": "research", "persona": "systematic_reviewer", "autonomy": "gated", "explicit_config_needed": "high", "adaptive_elements": ["select_search_databases", "choose_citation_manager", "apply_sync_policy"]},
    "expected_visible_behavior": ["acknowledge scan request", "explain search strategy", "request approval for external APIs", "scan after approval", "sync citations", "confirm completion"],
    "internal_behavior": ["create SolveRequest", "classify as systematic review", "load arXiv API", "load Semantic Scholar API", "load Zotero MCP", "apply external_action policy", "request approval", "invoke APIs: scan literature", "invoke MCP: sync Zotero", "generate EvidenceTable", "write case trace"],
    "artifacts": {"inputs": ["docs"], "intermediate": ["ContextBundle", "ScenarioDecision", "PolicyDecision"], "outputs": [{"name": "EvidenceTable", "type": "table", "lifecycle_state": "created", "domain_specific": True}, {"name": "CitationSyncLog", "type": "log", "lifecycle_state": "created", "domain_specific": False}], "persisted": ["CaseTrace"]},
    "capabilities": {"agents": ["systematic_reviewer"], "skills": ["research.systematic_scan"], "tools": ["context.read", "http.request", "mcp.invoke"], "external": [{"name": "arxiv.api", "type": "direct_api", "trust_level": "untrusted", "fallback_action": "use cached search results without live query"}, {"name": "semantic_scholar.api", "type": "direct_api", "trust_level": "untrusted", "fallback_action": "use cached search results without live query"}, {"name": "zotero.mcp", "type": "mcp", "trust_level": "untrusted", "fallback_action": "export citations locally without Zotero sync"}]},
    "policies": {"allow": ["read_project_files", "generate_report"], "ask": ["external_send", "mcp.invoke"], "deny": ["auto_publish_without_review", "personal_data_exposure"]},
    "gates": [{"gate_name": "external_api_approval", "severity": "block", "rationale": "External API queries may incur costs. Approval required."}, {"gate_name": "citation_sync_approval", "severity": "notify", "rationale": "Citation manager sync may overwrite existing library. Acknowledge."}],
    "memory": {"read": ["previous_scans"], "write_candidates": ["systematic_scan_summary"], "control_memory": []},
    "failure_modes": ["api_rate_limit", "zotero_unavailable", "policy_conflict_on_sync", "missing_access_to_paywalled_papers"],
    "configuration_effort": {"level": "domain_pack", "notes": "Requires research domain pack with citation manager integration."},
    "new_capabilities_introduced": ["citation_sync_log_artifact"],
    "concept_questions": ["should systematic scans require librarian approval"],
    "analysis_tags": ["external_action", "mcp", "governed_action", "multi_agent", "research"],
    "execution_result": {"envelope_type": "Artifact", "summary": "Artifact: EvidenceTable and CitationSyncLog", "confidence": "medium", "trace_reference": "CaseTrace"},
    "observability_requirements": {"metrics": True, "spans": True, "alerts": ["api_rate_limit", "zotero_sync_error"]},
})

# Append to existing scenarios
existing = []
with open("data/scenarios/scenarios.jsonl", "r") as f:
    for line in f:
        line = line.strip()
        if line:
            existing.append(json.loads(line))

all_scenarios = existing + scenarios

with open("data/scenarios/scenarios.jsonl", "w") as f:
    for s in all_scenarios:
        f.write(json.dumps(s, ensure_ascii=False) + "\n")

print(f"Total scenarios: {len(all_scenarios)} (added {len(scenarios)} new)")
